# 存储数据库连接信息
[connections.mysql]
dialect = "mysql"
driver = "pymysql"  # 需安装对应驱动（如pymysql、psycopg2等）
host = "localhost"
port = 3306
database = "your_db"
username = "root"
password = "xzy200312012"
query = { charset = "utf8mb4" } # 可选，处理中文编码问题